package com.karunadakala.source.repository

import com.karunadakala.source.model.ArtForm
import com.karunadakala.source.model.Artisan
import com.karunadakala.source.model.CulturalEvent
import com.karunadakala.source.model.MarkerKind
import com.karunadakala.source.model.WorkshopProgram

/**
 * Offline Karnataka cultural catalog used when Firestore is empty or unavailable.
 * Repositories emit this data immediately, then merge remote snapshots when present.
 */
object SampleData {

    val featuredBannerIds = listOf(
        "yakshagana",
        "bidriware",
        "kinnala",
        "ilkalsarees",
        "dollukunitha",
    )

    val artForms: List<ArtForm> = listOf(
        ArtForm(
            id = "yakshagana",
            name = "Yakshagana",
            history = "A vibrant coastal theatre tradition blending dance, music, and ornate costumes—often performed through the night during temple festivals.",
            region = "Coastal Karnataka",
            videoUrl = "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
            imageUrl = img("yakshagana"),
            originDistrict = "Udupi",
            famousArtisans = listOf("Guru Chittani Ramachandra Hegde", "Bhagavatha Mela lineage holders"),
            workshopAvailable = true,
        ),
        ArtForm(
            id = "bidriware",
            name = "Bidriware",
            history = "Metal inlay craft famed for blackened zinc alloy adorned with silver motifs—Bidar’s signature luxury handicraft.",
            region = "Hyderabad-Karnataka",
            videoUrl = "https://www.youtube.com/watch?v=jNQXAC9IVRw",
            imageUrl = img("bidriware"),
            originDistrict = "Bidar",
            famousArtisans = listOf("Bidar master craft clusters", "National award-winning metal artisans"),
            workshopAvailable = true,
        ),
        ArtForm(
            id = "kinnala",
            name = "Kinnala Toys",
            history = "Bright lacquered wooden toys and masks rooted in folk narratives—closely tied to ritual performance cycles.",
            region = "Kalyana Karnataka",
            videoUrl = "https://www.youtube.com/watch?v=9bZkp7q19f0",
            imageUrl = img("kinnala"),
            originDistrict = "Koppal region",
            famousArtisans = listOf("Hereditary Kinnala artisan families"),
            workshopAvailable = true,
        ),
        ArtForm(
            id = "ilkalsarees",
            name = "Ilkal Sarees",
            history = "Iconic cotton–silk sarees with distinctive checks and pallu motifs—woven traditions sustained across generations.",
            region = "Northern Karnataka",
            videoUrl = "https://www.youtube.com/watch?v=L_jWHffIx5E",
            imageUrl = img("ilkalsarees"),
            originDistrict = "Bagalkote–Vijayapura belt",
            famousArtisans = listOf("Ilkal weaving societies", "Women-led cooperative units"),
            workshopAvailable = false,
        ),
        ArtForm(
            id = "dollukunitha",
            name = "Dollu Kunitha",
            history = "Powerful drum dance featuring massive Dollu drums—performed at temple fairs celebrating communal vigour.",
            region = "Central Karnataka",
            videoUrl = "https://www.youtube.com/watch?v=tgbNymZ7vqY",
            imageUrl = img("dollukunitha"),
            originDistrict = "Davanagere",
            famousArtisans = listOf("Peripheral percussion ensembles", "Folk festival troupes"),
            workshopAvailable = true,
        ),
        ArtForm(
            id = "mysorepainting",
            name = "Mysore Painting",
            history = "Refined classical miniature style with gold leaf detail—depicting devotional themes with disciplined line work.",
            region = "Southern Karnataka",
            videoUrl = "https://www.youtube.com/watch?v=kJQP7kiw5Fk",
            imageUrl = img("mysorepainting"),
            originDistrict = "Mysuru",
            famousArtisans = listOf("Heritage ateliers around Mysuru palace precinct"),
            workshopAvailable = true,
        ),
        ArtForm(
            id = "channapatnatoys",
            name = "Channapatna Toys",
            history = "Rainbow-hued lac-turned wooden toys—‘gombegala ooru’ craftsmanship recognised across India.",
            region = "Ramanagara",
            videoUrl = "https://www.youtube.com/watch?v=RgKAFK5djSk",
            imageUrl = img("channapatnatoys"),
            originDistrict = "Ramanagara",
            famousArtisans = listOf("Channapatna artisan clusters"),
            workshopAvailable = true,
        ),
        ArtForm(
            id = "veeragase",
            name = "Veeragase",
            history = "High-energy devotional dance honouring Shiva—known for vigorous footwork, bells, and vigorous formations.",
            region = "Malnad & northern plains",
            videoUrl = "https://www.youtube.com/watch?v=CevxZvSJLk8",
            imageUrl = img("veeragase"),
            originDistrict = "Shivamogga",
            famousArtisans = listOf("Temple festival performers", "Rural guru-shishya groups"),
            workshopAvailable = true,
        ),
        ArtForm(
            id = "kasuti",
            name = "Kasuti Embroidery",
            history = "Intricate hand embroidery from North Karnataka sarees—geometric motifs passed through women's collectives.",
            region = "Northern Karnataka",
            videoUrl = "https://www.youtube.com/watch?v=OPf0YbXqDm0",
            imageUrl = img("kasuti"),
            originDistrict = "Dharwad",
            famousArtisans = listOf("Ilkal-Kasuti cooperative artisans"),
            workshopAvailable = true,
        ),
        ArtForm(
            id = "gamaka",
            name = "Gamaka",
            history = "Classical narrative singing style rendering Kannada epics with melodic elaboration.",
            region = "Statewide classical tradition",
            videoUrl = "https://www.youtube.com/watch?v=60ItHLz5WEA",
            imageUrl = img("gamaka"),
            originDistrict = "Mysuru",
            famousArtisans = listOf("Gamaka Sabha artists"),
            workshopAvailable = false,
        ),
    )

    val artisans: List<Artisan> = listOf(
        Artisan(
            id = "artisan_mysuru",
            name = "Lakshmi Devi",
            artForm = "Mysore Painting",
            district = "Mysuru",
            phone = "+919844000001",
            imageUrl = img("artisan_mysuru"),
            latitude = 12.2958,
            longitude = 76.6394,
            bio = "Heritage painter mentoring young artists in traditional gold-leaf Mysore style.",
            experienceYears = 22,
            village = "Nazarbad",
            markerKind = MarkerKind.WORKSHOP,
            workshops = listOf("Gold leaf fundamentals", "Composition masterclass"),
            products = listOf("Krishna panel", "Mini devotee set"),
        ),
        Artisan(
            id = "artisan_dharwad",
            name = "Basavaraj Toravi",
            artForm = "Dollu Kunitha",
            district = "Dharwad",
            phone = "+919844000002",
            imageUrl = img("artisan_dharwad"),
            latitude = 15.4589,
            longitude = 75.0078,
            bio = "Percussion choreographer touring temple fairs across Malnad.",
            experienceYears = 18,
            village = "Annigeri",
            markerKind = MarkerKind.PERFORMANCE,
            workshops = listOf("Rhythm ensemble basics"),
            products = listOf("Custom Dollu drums"),
        ),
        Artisan(
            id = "artisan_bidar",
            name = "Ayaz Ahmed",
            artForm = "Bidriware",
            district = "Bidar",
            phone = "+919844000003",
            imageUrl = img("artisan_bidar"),
            latitude = 17.9104,
            longitude = 77.5199,
            bio = "Silver inlay artisan documenting Bidri motifs for apprentices.",
            experienceYears = 25,
            village = "Bidar fort precinct",
            markerKind = MarkerKind.WORKSHOP,
            workshops = listOf("Inlay beginners", "Patina finishing lab"),
            products = listOf("Rose vase", "Mughal motif tray"),
        ),
        Artisan(
            id = "artisan_vijayapura",
            name = "Sharada Hullannavar",
            artForm = "Ilkal Sarees",
            district = "Vijayapura",
            phone = "+919844000004",
            imageUrl = img("artisan_vijayapura"),
            latitude = 16.8302,
            longitude = 75.7100,
            bio = "Weaver documenting Ilkal pallu geometry with cooperative trainees.",
            experienceYears = 16,
            village = "Hungund cluster",
            markerKind = MarkerKind.WORKSHOP,
            workshops = listOf("Warp setup clinic"),
            products = listOf("Traditional checks saree"),
        ),
        Artisan(
            id = "artisan_chitradurga",
            name = "Hanumantha Reddy",
            artForm = "Veeragase",
            district = "Chitradurga",
            phone = "+919919000005",
            imageUrl = img("artisan_chitradurga"),
            latitude = 14.2254,
            longitude = 76.3980,
            bio = "Leads Veeragase cohorts at regional heritage festivals.",
            experienceYears = 20,
            village = "Molakalmuru belt",
            markerKind = MarkerKind.PERFORMANCE,
            workshops = listOf("Weekend intensive basics"),
            products = listOf("Performance attire bundle"),
        ),
        Artisan(
            id = "artisan_udupi",
            name = "Krishna Marakala",
            artForm = "Yakshagana",
            district = "Udupi",
            phone = "+919820000006",
            imageUrl = img("artisan_udupi"),
            latitude = 13.3409,
            longitude = 74.7421,
            bio = "Bhagavatha vocalist coaching coastal Yakshagana students.",
            experienceYears = 28,
            village = "Kadiyali",
            markerKind = MarkerKind.PERFORMANCE,
            workshops = listOf("Bhagavatha essentials", "Stage movement lab"),
            products = listOf("Mini crown replica"),
        ),
        Artisan(
            id = "artisan_ramanagara",
            name = "Ramesh Gowda",
            artForm = "Channapatna Toys",
            district = "Ramanagara",
            phone = "+919845000007",
            imageUrl = img("artisan_ramanagara"),
            latitude = 12.6518,
            longitude = 77.2088,
            bio = "Lac-turning mentor at the toy artisans cooperative in Channapatna.",
            experienceYears = 19,
            village = "Channapatna",
            markerKind = MarkerKind.WORKSHOP,
            workshops = listOf("Lathe safety", "Natural dye finishing"),
            products = listOf("Puzzle sets", "Rattle toys"),
        ),
        Artisan(
            id = "artisan_koppal",
            name = "Shivappa Kinnala",
            artForm = "Kinnala Toys",
            district = "Koppal",
            phone = "+919845000008",
            imageUrl = img("artisan_koppal"),
            latitude = 15.3500,
            longitude = 76.1500,
            bio = "Preserves Kinnala mask carving for Dasara processions.",
            experienceYears = 24,
            village = "Kinhal",
            markerKind = MarkerKind.WORKSHOP,
            workshops = listOf("Mask carving intro", "Lacquer burnishing"),
            products = listOf("Folk masks", "Puppet sets"),
        ),
    )

    val events: List<CulturalEvent> = listOf(
        CulturalEvent(
            id = "evt_udupi_yaksha",
            title = "Yakshagana Night",
            artForm = "Yakshagana",
            district = "Udupi",
            date = "2026-06-15",
            venue = "Town Hall Grounds, Udupi",
            imageUrl = img("evt_udupi_yaksha"),
        ),
        CulturalEvent(
            id = "evt_tumkur_dollu",
            title = "Dollu Kunitha Festival",
            artForm = "Dollu Kunitha",
            district = "Tumakuru",
            date = "2026-07-03",
            venue = "Amphitheatre, Tumakuru",
            imageUrl = img("evt_tumkur_dollu"),
        ),
        CulturalEvent(
            id = "evt_bidar_expo",
            title = "Bidriware Expo",
            artForm = "Bidriware",
            district = "Bidar",
            date = "2026-08-22",
            venue = "Bidar Heritage Plaza",
            imageUrl = img("evt_bidar_expo"),
        ),
        CulturalEvent(
            id = "evt_mysuru_palette",
            title = "Mysuru Palette Week",
            artForm = "Mysore Painting",
            district = "Mysuru",
            date = "2026-09-10",
            venue = "Kalamandira, Mysuru",
            imageUrl = img("evt_mysuru_palette"),
        ),
        CulturalEvent(
            id = "evt_ramanagara_craft",
            title = "Channapatna Craft Carnival",
            artForm = "Channapatna Toys",
            district = "Ramanagara",
            date = "2026-10-02",
            venue = "Town Square, Channapatna",
            imageUrl = img("evt_ramanagara_craft"),
        ),
        CulturalEvent(
            id = "evt_hampi_heritage",
            title = "Hampi Heritage Evenings",
            artForm = "Veeragase",
            district = "Ballari",
            date = "2026-11-18",
            venue = "Hampi Bazaar Amphitheatre",
            imageUrl = img("evt_hampi_heritage"),
        ),
        CulturalEvent(
            id = "evt_mangaluru_coastal",
            title = "Coastal Folk Mela",
            artForm = "Yakshagana",
            district = "Dakshina Kannada",
            date = "2026-12-05",
            venue = "Kadri Park, Mangaluru",
            imageUrl = img("evt_mangaluru_coastal"),
        ),
        CulturalEvent(
            id = "evt_hassan_weave",
            title = "Ilkal & Kasuti Textile Week",
            artForm = "Ilkal Sarees",
            district = "Hassan",
            date = "2027-01-14",
            venue = "District Kalakshetra, Hassan",
            imageUrl = img("evt_hassan_weave"),
        ),
    )

    val workshopPrograms: List<WorkshopProgram> = listOf(
        WorkshopProgram(
            id = "ws_yaksha_weekend",
            title = "Weekend Yakshagana Immersion",
            artForm = "Yakshagana",
            hostName = "Krishna Marakala",
            district = "Udupi",
            schedule = "Sat–Sun, 9:00 AM",
            duration = "2 days",
            feeInr = 1200,
        ),
        WorkshopProgram(
            id = "ws_bidri_inlay",
            title = "Bidri Silver Inlay Basics",
            artForm = "Bidriware",
            hostName = "Ayaz Ahmed",
            district = "Bidar",
            schedule = "Mon–Wed, 10:00 AM",
            duration = "3 days",
            feeInr = 2500,
        ),
        WorkshopProgram(
            id = "ws_mysore_gold",
            title = "Mysore Painting Gold Leaf",
            artForm = "Mysore Painting",
            hostName = "Lakshmi Devi",
            district = "Mysuru",
            schedule = "Fri evenings",
            duration = "4 sessions",
            feeInr = 1800,
        ),
        WorkshopProgram(
            id = "ws_channapatna_turn",
            title = "Lac Turned Toy Making",
            artForm = "Channapatna Toys",
            hostName = "Channapatna artisan cluster",
            district = "Ramanagara",
            schedule = "Daily batches",
            duration = "1 day",
            feeInr = 900,
        ),
        WorkshopProgram(
            id = "ws_dollu_ensemble",
            title = "Dollu Kunitha Ensemble Drills",
            artForm = "Dollu Kunitha",
            hostName = "Basavaraj Toravi",
            district = "Dharwad",
            schedule = "Sunday intensive",
            duration = "6 hours",
            feeInr = 750,
        ),
        WorkshopProgram(
            id = "ws_kinnala_mask",
            title = "Kinnala Mask & Lacquer",
            artForm = "Kinnala Toys",
            hostName = "Koppal heritage guild",
            district = "Koppal",
            schedule = "First week monthly",
            duration = "2 days",
            feeInr = 1100,
        ),
    )

    private fun img(seed: String): String = "https://picsum.photos/seed/$seed/900/520"
}
